/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controller.ControladorClientesC;
import controller.ControladorClientesIBM;
import controller.ControladorEspecialistasIBM;
import controller.ControladorMascotasIBM;

/**
 *
 * @author ciroi
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mascotasLBL = new javax.swing.JLabel();
        clientesLBL = new javax.swing.JLabel();
        especialistasLBL = new javax.swing.JLabel();
        clientesMascotasLBL = new javax.swing.JLabel();
        cuentasLBL = new javax.swing.JLabel();
        manejarClientesBTN = new javax.swing.JButton();
        consultarClientesBTN = new javax.swing.JButton();
        manejarMascotasIBM = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        manejarEspecialistasBTN = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mascotasLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        mascotasLBL.setText("MASCOTAS");

        clientesLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clientesLBL.setText("CLIENTES");

        especialistasLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        especialistasLBL.setText("ESPECIALISTAS");

        clientesMascotasLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        clientesMascotasLBL.setText("CLIENTES<->MASCOTAS");

        cuentasLBL.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cuentasLBL.setText("CUENTAS");

        manejarClientesBTN.setText("Manejar");
        manejarClientesBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manejarClientesBTNMouseClicked(evt);
            }
        });

        consultarClientesBTN.setText("Consultar");
        consultarClientesBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultarClientesBTNMouseClicked(evt);
            }
        });

        manejarMascotasIBM.setText("Manejar");
        manejarMascotasIBM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manejarMascotasIBMMouseClicked(evt);
            }
        });

        jButton4.setText("Manejar");

        manejarEspecialistasBTN.setText("Manejar");
        manejarEspecialistasBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manejarEspecialistasBTNMouseClicked(evt);
            }
        });

        jButton6.setText("Manejar");

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 30)); // NOI18N
        jLabel1.setText("GESTIÓN DE TIENDA DE HIGIENE DE MASCOTAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(manejarClientesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(consultarClientesBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(manejarMascotasIBM, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(manejarEspecialistasBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clientesLBL)
                        .addGap(52, 52, 52)
                        .addComponent(clientesMascotasLBL)
                        .addGap(44, 44, 44)
                        .addComponent(mascotasLBL)
                        .addGap(48, 48, 48)
                        .addComponent(especialistasLBL)
                        .addGap(45, 45, 45)
                        .addComponent(cuentasLBL)
                        .addGap(82, 82, 82))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientesLBL)
                    .addComponent(mascotasLBL)
                    .addComponent(especialistasLBL)
                    .addComponent(clientesMascotasLBL)
                    .addComponent(cuentasLBL))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manejarClientesBTN)
                    .addComponent(manejarMascotasIBM)
                    .addComponent(jButton4)
                    .addComponent(manejarEspecialistasBTN)
                    .addComponent(jButton6))
                .addGap(39, 39, 39)
                .addComponent(consultarClientesBTN)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manejarClientesBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manejarClientesBTNMouseClicked
        ControladorClientesIBM.iniciar(this);
    }//GEN-LAST:event_manejarClientesBTNMouseClicked

    private void consultarClientesBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultarClientesBTNMouseClicked
        ControladorClientesC.iniciar(this);
    }//GEN-LAST:event_consultarClientesBTNMouseClicked

    private void manejarEspecialistasBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manejarEspecialistasBTNMouseClicked
        ControladorEspecialistasIBM.iniciar(this);
    }//GEN-LAST:event_manejarEspecialistasBTNMouseClicked

    private void manejarMascotasIBMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manejarMascotasIBMMouseClicked
        ControladorMascotasIBM.iniciar(this);
    }//GEN-LAST:event_manejarMascotasIBMMouseClicked

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientesLBL;
    private javax.swing.JLabel clientesMascotasLBL;
    private javax.swing.JButton consultarClientesBTN;
    private javax.swing.JLabel cuentasLBL;
    private javax.swing.JLabel especialistasLBL;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manejarClientesBTN;
    private javax.swing.JButton manejarEspecialistasBTN;
    private javax.swing.JButton manejarMascotasIBM;
    private javax.swing.JLabel mascotasLBL;
    // End of variables declaration//GEN-END:variables
}
